import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { JSDOM, VirtualConsole } from 'jsdom';
const app = readFileSync(new URL('../app.js', import.meta.url), 'utf8');
const html = readFileSync(new URL('../index.html', import.meta.url), 'utf8');
const handler = app.slice(app.indexOf('  async function submitLiterature('), app.indexOf('  async function submitCourse('));
const dialog = html.slice(html.indexOf('  <dialog class="modal literature-modal"'), html.indexOf('  </dialog>', html.indexOf('  <dialog class="modal literature-modal"')) + 11);
const dom = new JSDOM(dialog, { url: 'https://fixture.test', runScripts: 'outside-only', virtualConsole: new VirtualConsole() });
const w = dom.window, d = w.document, form = d.querySelector('form'), button = d.querySelector('#literature-submit'), error = d.querySelector('#literature-error');
const values = new Map(), requests = []; let respond = async () => { throw new Error('模拟保存失败'); }, cleared = 0, closed = 0, toasts = 0;
w.elements = { literatureForm: form, literatureSubmit: button, literatureError: error, literatureDialog: d.querySelector('dialog') };
w.state = { session: 'fixture', dashboard: { profile: { sub: 'student1' }, week: { id: '2026-W37' }, literature: { items: [], mineCount: 0 } } };
w.DEMO_MODE = false; w.draftScope = () => '2026-W37'; w.draftKeys = { literature: 'literature' };
w.privateDrafts = { get: key => values.get(key), set: (key, _, value) => values.set(key, value), remove: key => values.delete(key) };
w.pendingRequestId = key => { if (!values.has(key)) values.set(key, 'req-' + (requests.length + 1)); return values.get(key); };
w.saveDraft = () => values.set('literature', JSON.stringify(Object.fromEntries(new w.FormData(form))));
w.clearDraft = () => { cleared++; values.delete('literature'); };
w.closeDialog = () => { closed++; }; w.renderActiveView = () => {}; w.showToast = () => { toasts++; };
w.request = async (_, options) => { requests.push(JSON.parse(options.body)); return respond(); };
w.eval(handler); form.addEventListener('submit', w.submitLiterature);
const wait = async predicate => { for (let i = 0; i < 100; i++) { if (predicate()) return; await new Promise(r => setTimeout(r, 5)); } throw Error('UI timeout'); };
const fill = () => { form.elements.title.value = '合成论文'; form.elements.contribution.value = '合成贡献'; form.elements.noteUrl.value = 'example.com/note'; };
const success = { ok: true, recordId: 'confirmed', readBackVerified: true, literature: { items: [], mineCount: 1 } };
try {
  assert.equal(form.noValidate, true); assert.equal(error.parentElement.className, 'modal-actions');
  button.click(); await wait(() => !button.disabled); assert.equal(requests.length, 0); assert.match(error.textContent, /请填写论文标题/); assert.equal(error.hidden, false);
  assert.equal(form.elements.noteUrl.required, false);
  respond = async () => success;
  fill(); form.elements.noteUrl.value = ''; button.click(); await wait(() => !button.disabled);
  assert.equal(requests[0].noteUrl, ''); assert.equal(closed, 1); assert.equal(cleared, 1); assert.equal(toasts, 1);
  requests.length = 0; closed = 0; cleared = 0; toasts = 0;
  respond = async () => { throw new Error('模拟保存失败'); };
  fill(); form.elements.noteUrl.value = 'http://example.com'; button.click(); await wait(() => !button.disabled); assert.match(error.textContent, /https/); assert.equal(requests.length, 0);
  fill(); form.requestSubmit(button); await wait(() => !button.disabled);
  assert.equal(requests[0].noteUrl, 'https://example.com/note', 'Enter/requestSubmit normalizes before validity checks');
  assert.match(error.textContent, /模拟保存失败/); assert.equal(error.hidden, false); assert.equal(form.elements.title.value, '合成论文'); assert.equal(cleared, 0);
  let finish; respond = () => new Promise(resolve => { finish = resolve; }); button.click(); await wait(() => typeof finish === 'function');
  button.click(); form.dispatchEvent(new w.Event('submit', { bubbles: true, cancelable: true })); assert.equal(requests.length, 2);
  assert.equal(form.elements.title.disabled, true); assert.equal(requests[0].requestId, requests[1].requestId);
  finish({}); await wait(() => !button.disabled); assert.match(error.textContent, /尚未确认/); assert.equal(cleared, 0); assert.equal(form.elements.title.disabled, false);
  respond = async () => success; button.click(); await wait(() => !button.disabled); assert.equal(cleared, 1); assert.equal(closed, 1); assert.equal(toasts, 1); assert.equal(w.state.dashboard.literature.mineCount, 1);
  fill(); respond = () => new Promise(resolve => { finish = resolve; }); finish = null; button.click(); await wait(() => typeof finish === 'function');
  w.state.dashboard.profile.sub = 'student2'; finish(success); await wait(() => !button.disabled); assert.equal(cleared, 1); assert.equal(closed, 1); assert.equal(toasts, 1);
  console.log('PASS literature form: real submit validation, visible Chinese errors, bare URLs/Enter, draft preservation, duplicate click, uncertain response, confirmed success and account switch');
} finally { dom.window.close(); }
