import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {JSDOM} from 'jsdom';
import {checkMemberIntake} from './src/member-intake.js';
import service from './src/index.js';
const person = {record_id:'fixture',fields:{'姓名':'测试成员','人员编号':'P-101','飞书成员':[{id:'ou_fixture'}],'人员边界':'团队内','成员类别':'博士','人员状态':'在组'}};
const actor = {sub:'ou_admin',duties:['管理员'],memberRecord:{fields:{'人员边界':'团队内','成员类别':'RA'}}};
const plan = {name:'测试成员',account:'ou_fixture',boundary:'团队内',category:'临时',organization:'未加入',start:'2026-09-15',end:'',weekly:'需要',weeklyStart:'2026-09-14',learning:'阅读',literatureRead:'允许',literatureShare:'允许',literatureRequired:'不考核',projects:'',notes:''};
const before = JSON.stringify(person);
const result = checkMemberIntake(actor,plan,[person]);
assert.equal(result.accessGranted,false); assert.equal(result.saved,false); assert.equal(JSON.stringify(person),before);
assert.equal(result.checks[0].status,'已匹配现有记录');
for (const bad of [{...actor,duties:[]},{...actor,memberRecord:{fields:{'人员边界':'团队外','成员类别':'PI'}}}]) assert.throws(()=>checkMemberIntake(bad,plan,[person]),{status:403});
for (const extra of [{weeklyStart:'2026-09-15'},{end:'2026-09-01'},{start:'2026-02-30'},{projects:'*'},{literatureRead:'不允许'},{admin:true}]) assert.throws(()=>checkMemberIntake(actor,{...plan,...extra},[person]),{status:400});
assert.equal(checkMemberIntake(actor,{...plan,account:'测试成员'},[person]).checks[0].status,'待核验');
assert.equal((await service.fetch(new Request('https://fixture.test/api/admin/member-intake/check',{method:'POST',body:JSON.stringify(plan)}),{SESSION_SECRET:'fixture-secret'})).status,401);
const originalFetch = globalThis.fetch;
const env = {SESSION_SECRET:'fixture-intake-secret',MEMBERS_TABLE_ID:'members',MEMBERS_BASE_APP_TOKEN:'fixture',FEISHU_APP_ID:'fixture',FEISHU_APP_SECRET:'fixture',FRONTEND_URL:'https://fixture.test'};
let reads = 0;
const member = {record_id:'admin',fields:{...person.fields,'飞书成员':[{id:'ou_admin'}],'人员编号':'P-102','系统职责':['管理员']}};
globalThis.fetch = async (url,options={}) => {
  assert.equal(new URL(url).hostname,'open.feishu.cn');
  if(String(url).endsWith('/tenant_access_token/internal')) return Response.json({code:0,tenant_access_token:'fixture-token',expire:7200});
  assert.equal(options.method,'GET','Intake must not mutate Feishu'); reads++;
  return Response.json({code:0,data:{items:[member,person],has_more:false}});
};
try {
  const payload=Buffer.from(JSON.stringify({purpose:'session',sub:'ou_admin',exp:Math.floor(Date.now()/1000)+3600})).toString('base64url');
  const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(env.SESSION_SECRET),{name:'HMAC',hash:'SHA-256'},false,['sign']);
  const signature=Buffer.from(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(payload))).toString('base64url');
  const call=()=>service.fetch(new Request('https://fixture.test/api/admin/member-intake/check',{method:'POST',headers:{Authorization:'Bearer '+payload+'.'+signature},body:JSON.stringify(plan)}),env);
  assert.equal((await call()).status,200);
  member.fields['系统职责']=[];
  assert.equal((await call()).status,403,'Revoked manager cannot reuse session role');
  assert.equal(reads,2,'Each preview freshly checks identity');
} finally {globalThis.fetch=originalFetch;}

const source = readFileSync(new URL('../app.js',import.meta.url),'utf8');
const functionSource = source.slice(source.indexOf('  function openMemberIntake()'),source.indexOf('  function renderManager()'));
const dom = new JSDOM('<!doctype html><body></body>',{url:'https://fixture.test',runScripts:'outside-only'});
const w = dom.window;
w.state = {activeRole:'student',dashboard:{profile:{sub:'ou_admin',roles:['student']}}};
w.escapeHtml = x=>String(x).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
w.showDialog = d=>d.setAttribute('open',''); w.closeDialog=d=>d.dispatchEvent(new w.Event('close'));
let calls=0;
w.request=async()=>{calls++;return result;};
w.eval(functionSource);
w.openMemberIntake(); assert.equal(w.document.querySelector('dialog'),null);
w.state.activeRole='manager'; w.openMemberIntake(); assert.equal(w.document.querySelector('dialog'),null,'UI role name cannot grant access');
w.state.dashboard.profile.roles=['manager']; w.openMemberIntake();
const form=w.document.querySelector('form'); assert.ok(form);
assert.match(form.textContent,/不直接开通权限/);
form.elements.template.value='组内临时成员'; form.elements.template.dispatchEvent(new w.Event('change',{bubbles:true}));
assert.equal(form.elements.literatureRequired.value,'不考核');
for(const [k,v] of Object.entries(plan)) form.elements[k].value=v;
form.dispatchEvent(new w.Event('submit',{cancelable:true}));
await new Promise(resolve=>setTimeout(resolve,0));
assert.equal(calls,1); assert.match(form.querySelector('[data-intake-result]').textContent,/未开通/);
w.closeDialog(w.document.querySelector('dialog')); assert.equal(w.document.querySelector('dialog'),null);
dom.window.close();
console.log('PASS member intake: admin guard, anonymous denial, validation, no mutations, UI template and check');
